feat: public picture & competition apply of points
opensourceways/xihe-server pull request #540
Opened 2023-09-08 08:09 UTC by VictorZhou123

2023-09-10 03:04 UTC, pkking commented on bigmodel/domain/message/message.go
> +		Details:   nil,
desc没有填?

2023-09-11 01:27 UTC, VictorZhou123 commented on bigmodel/domain/message/message.go
> +		Details:   nil,
没找到有用的信息填进desc里

2023-09-11 03:05 UTC, zengchen1024 requested changes

2023-09-11 03:05 UTC, zengchen1024 commented on competition/domain/message/message.go
> +func (msg *CompetitionMsg) GenApplyMsg(
不应该在这里定义生成消息的方法

2023-09-15 03:03 UTC, closed without merging