update message of training
opensourceways/xihe-server pull request #557
Opened 2023-09-15 06:07 UTC by VictorZhou123

2023-09-18 10:54 UTC, zengchen1024 requested changes

2023-09-18 10:54 UTC, zengchen1024 commented on app/training.go
> +	}); err != nil {
建议采用如下格式
err = s.sender.SendTrainingCreated(&domain.TrainingCreatedEvent{
		Account:        user,
		TrainingIndex:  index,
		TrainingInputs: config.Inputs,
	})
 if err != nil {

2023-09-18 10:54 UTC, zengchen1024 commented on controller/messagequeue/training.go
> +package messagequeue
把 messagequeue 挪到跟controller平行的目录

2023-09-18 10:54 UTC, zengchen1024 commented on controller/messagequeue/training.go
> +	TrainingCreated string `json:"training_created" required:"true"`
TrainingCreated 挪到 TrainingConfig。简单点

2023-09-18 10:54 UTC, zengchen1024 commented on controller/messagequeue/training.go
> +	MaxRetry         int    `json:"max_retry"         required:"true"`
MaxRetry 设置默认值

2023-09-18 10:54 UTC, zengchen1024 commented on controller/messagequeue/training.go
> +func (c *consumer) retry(f func(bool) error, interval time.Duration) (err error) {
https://github.com/opensourceways/xihe-server/blob/dev/utils/util.go#L125 直接使用这个函数吧

2023-09-18 10:54 UTC, zengchen1024 commented on controller/messagequeue/training.go
> +func (c *consumer) handleEventTrainCreated(info *domain.TrainingIndex) error {
s/handleEventTrainCreated/createJob

2023-09-18 10:54 UTC, zengchen1024 commented on message-server/config.go
> +	TrainingTopics msgqueue.TopicConfig `json:"training_topics"`
TrainingCreated string `json:"training_created"`

2023-09-18 10:54 UTC, zengchen1024 commented on message-server/main.go
> +func trainingSubscribeMessage(log *logrus.Entry, cfg *configuration) error {
trainingSubscribesMessage

2023-09-18 10:54 UTC, zengchen1024 commented on server/gin.go
> +			v1, trainingAdapter, training, model, proj, dataset, trainingSender,
s/trainingSender/messages.NewTrainingMessageAdapter(&cfg.Training.Message, publisher) 记得换行

2023-09-18 11:02 UTC, VictorZhou123 commented on app/training.go
> +	}); err != nil {
> 建议采用如下格式 err = s.sender.SendTrainingCreated(&domain.TrainingCreatedEvent{ Account: user, TrainingIndex: index, TrainingInputs: config.Inputs, }) if err != nil {

done

2023-09-18 11:05 UTC, VictorZhou123 commented on controller/messagequeue/training.go
> +package messagequeue
> 把 messagequeue 挪到跟controller平行的目录

done

2023-09-18 11:12 UTC, VictorZhou123 commented on controller/messagequeue/training.go
> +	TrainingCreated string `json:"training_created" required:"true"`
> TrainingCreated 挪到 TrainingConfig。简单点

done

2023-09-18 11:22 UTC, VictorZhou123 commented on controller/messagequeue/training.go
> +func (c *consumer) retry(f func(bool) error, interval time.Duration) (err error) {
> https://github.com/opensourceways/xihe-server/blob/dev/utils/util.go#L125 直接使用这个函数吧

done

2023-09-18 11:23 UTC, VictorZhou123 commented on controller/messagequeue/training.go
> +func (c *consumer) handleEventTrainCreated(info *domain.TrainingIndex) error {
> s/handleEventTrainCreated/createJob

done

2023-09-18 11:23 UTC, VictorZhou123 commented on message-server/config.go
> +	TrainingTopics msgqueue.TopicConfig `json:"training_topics"`
> TrainingCreated string `json:"training_created"`

done

2023-09-18 11:24 UTC, VictorZhou123 commented on message-server/main.go
> +func trainingSubscribeMessage(log *logrus.Entry, cfg *configuration) error {
> trainingSubscribesMessage

done

2023-09-18 11:25 UTC, VictorZhou123 commented on server/gin.go
> +			v1, trainingAdapter, training, model, proj, dataset, trainingSender,
> s/trainingSender/messages.NewTrainingMessageAdapter(&cfg.Training.Message, publisher) 记得换行

done

2023-09-18 12:15 UTC, zengchen1024 requested changes

2023-09-18 12:15 UTC, zengchen1024 commented on config/training.go
> +	Message messages.TrainingConfig
Message 缺少tag

2023-09-18 12:15 UTC, zengchen1024 commented on messagequeue/training.go
> +func (c *consumer) handleEventCreateJob(info *domain.TrainingIndex) error {
s/handleEventCreateJob/createJob

2023-09-18 12:15 UTC, zengchen1024 commented on messagequeue/training.go
> +			c.log.Errorf(
logrus.Errorf

2023-09-18 12:15 UTC, zengchen1024 commented on message-server/config.go
> +
去掉 34， 35行，用messagequeue中的config作为training的config

2023-09-18 14:53 UTC, VictorZhou123 commented on server/gin.go
> +				&cfg.Training.Message, publisher,
> messages.NewTrainingMessageAdapter 放到273行

done

2023-09-18 14:53 UTC, VictorZhou123 commented on config/training.go
> +	Message messages.TrainingConfig
> Message 缺少tag

done

2023-09-18 14:54 UTC, VictorZhou123 commented on messagequeue/training.go
> +func (c *consumer) handleEventCreateJob(info *domain.TrainingIndex) error {
> createJob

done

2023-09-18 14:56 UTC, VictorZhou123 commented on messagequeue/training.go
> +			c.log.Errorf(
> logrus.Errorf

done

2023-09-18 15:07 UTC, VictorZhou123 commented on message-server/config.go
> +
> 去掉 34， 35行，用messagequeue中的config作为training的config

done

2023-09-19 01:44 UTC, VictorZhou123 commented on messagequeue/training.go
> +func (cfg *TrainingConfig) SetDefault() {
> TrainingCreated 应该作为参数传入

done

2023-09-19 02:39 UTC, zengchen1024 requested changes

2023-09-19 02:39 UTC, zengchen1024 commented on message-server/config.go
> +	if cfg.Training.MaxRetry <= 0 {
删除73， 74

2023-09-19 02:39 UTC, zengchen1024 commented on server/gin.go
> +				&cfg.Training.Message, publisher),
messages.NewTrainingMessageAdapter(
				&cfg.Training.Message, publisher，
),

2023-09-19 02:39 UTC, zengchen1024 commented on message-server/main.go
> +		trainingEndpoint: cfg.Training.TrainingEndpoint,
为什么还要配置trainingEndpoint

2023-09-19 02:39 UTC, zengchen1024 commented on server/gin.go
> -	// user := repositories.NewUserRepository(
删除无效的配置

2023-09-19 03:01 UTC, VictorZhou123 commented on message-server/config.go
> +	if cfg.Training.MaxRetry <= 0 {
> 删除73， 74

done

2023-09-19 03:02 UTC, VictorZhou123 commented on message-server/main.go
> +		trainingEndpoint: cfg.Training.TrainingEndpoint,
> 为什么还要配置trainingEndpoint

done

2023-09-19 06:19 UTC, zengchen1024 requested changes

2023-09-19 06:19 UTC, zengchen1024 commented on message-server/config.go
> +	if cfg.MaxRetry == 0 {
<=

2023-09-19 06:34 UTC, merged