update message of useraction
opensourceways/xihe-server pull request #566
Opened 2023-09-18 11:24 UTC by Liran333

2023-09-18 12:42 UTC, zengchen1024 requested changes

2023-09-18 12:42 UTC, zengchen1024 commented on message-server/config.go
> +	UserSignedUp string `json:"user_register"      required:"true"`
tag的格式保持一致“名词_过去式”

2023-09-18 12:42 UTC, zengchen1024 commented on message-server/main.go
> +		user: userapp.NewUserService(userRepo, nil, nil, nil, nil, nil),
参考points的实现方式，创建messagequeue目录来单独实现user相关的订阅

2023-09-18 12:42 UTC, zengchen1024 commented on server/gin.go
> +	usermsg "github.com/opensourceways/xihe-server/user/infrastructure/messageadapter"
放在正确的位置

2023-09-18 12:42 UTC, zengchen1024 commented on user/app/updatebaseinfo.go
> +	} else if b && cmd.AvatarId != nil && cmd.AvatarId != user.AvatarId {
有无更优化的判断方式，比如cmd中添加小写的变量来存储是否更新了该字段
发送消息不应该在这里

2023-09-18 12:42 UTC, zengchen1024 commented on user/infrastructure/messageadapter/impl.go
> +	BindEmail    common.TopicConfig `json:"bind_email"`
BindEmail 没有使用
tag命名“名词_过去式”

2023-09-18 12:42 UTC, zengchen1024 commented on user/infrastructure/messageadapter/impl.go
> +func (impl *messageAdapter) SendSetAvatarIdEvent(v *domain.UserAvatarSetEvent) error {
SendUserAvatarSetEvent 其他参考修改

2023-09-19 11:58 UTC, pkking commented on message-server/config.go
> +	UserFollowingTopics usermq.TopicConfig `json:"user-following-topics"`
加上`required:"true"`

2023-09-19 11:58 UTC, pkking commented on message-server/config.go
> +	User       user.Config          `json:"user"`
required:"true"

2023-09-19 11:58 UTC, pkking commented on user/messagequeue/user.go
> +	FollowingAdd    string `json:"following_add"`
required:"true"

2023-09-19 11:58 UTC, pkking commented on user/infrastructure/messageadapter/impl.go
> +	UserSignedUp common.TopicConfig `json:"sign_up"`
都需要 required:"true"

2023-09-19 12:27 UTC, pkking commented on user/config.go
> +	Message usermsg.Config `json:"message"`
required

2023-09-20 02:08 UTC, zengchen1024 requested changes

2023-09-20 02:08 UTC, zengchen1024 commented on user/app/updatebaseinfo.go
> +	} else if b && cmd.AvatarId != nil && cmd.AvatarId != user.AvatarId {
怎么不修改呢？ 避免多重if else

2023-09-20 02:08 UTC, zengchen1024 commented on user/app/user.go
> +	err = s.sender.SendUserSignedUpEvent(&domain.UserSignedUpEvent{
不要改变原来的逻辑，原来的逻辑是忽略错误，为啥这里要返回错误

2023-09-20 02:08 UTC, zengchen1024 commented on message-server/main.go
> +		userapp.NewUserService(userrepo.NewUserRepo(
格式一致，userapp.NewUserService 的部分参数是按行写的，那么所有参数都独立一行，否则代码可读性很差。

这个函数的参数不是所有都需要，不需要的传nil即可。

2023-09-20 02:08 UTC, zengchen1024 commented on message-server/config.go
> +	User       user.Config                 `json:"user"         required:"true"`
不需要user的配置

2023-09-20 02:32 UTC, zengchen1024 requested changes

2023-09-20 02:32 UTC, zengchen1024 commented on message-server/config.go
> +	UserFollowingTopics usermq.TopicConfig `json:"user-following-topics" required:"true"`
定义清楚每个topic

2023-09-20 02:32 UTC, zengchen1024 commented on user/app/updatebaseinfo.go
> +	} else if b && cmd.AvatarId != nil && cmd.AvatarId != user.AvatarId {
忽略错误

2023-09-20 14:40 UTC, pkking commented on user/infrastructure/messageadapter/impl.go
> +		com: common.MsgNormal{
MsgNormal: common.MsgNormal{

2023-09-20 14:40 UTC, pkking commented on user/messagequeue/user.go
> +func Subscribe(s app.UserService, subscriber message.Subscriber) (err error) {
增加一个topics *TopicConfig参数

2023-09-20 14:40 UTC, pkking commented on user/messagequeue/user.go
> +	topicmsg := TopicConfig{}
删掉这一行

2023-09-20 14:40 UTC, pkking commented on message-server/main.go
> +		kafka.SubscriberAdapter(),
增加一个参数， &topics.UserTopics

2023-09-21 01:43 UTC, Liran333 commented on user/infrastructure/messageadapter/impl.go
> +	return impl.publisher.Publish(cfg.Topic, &msg, nil)
上面定义了cfg := &impl.cfg.FollowingRemoved，这里直接打点＋Topic

2023-09-26 08:30 UTC, closed without merging